server:  port: 80 
spring:
  sql:    init:      continue-on-error: true
  main:    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none  datasource:
    type: 
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:      minimum-idle: 1
      maximum-pool-size: 1
