spring:
  sql:    init:      continue-on-error: true
  main:    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update  datasource:
    type: 
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password:     driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:      minimum-idle: 1
      maximum-pool-size: 1
