spring:
  h2:
    console:      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:llms
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1