spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password:     driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:      minimum-idle: 1
      maximum-pool-size: 1