spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    password: ''
    username: sa
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
