server:  port: 80 

mqtt:  topic: requisitions  client-id: rms-${COMPUTERNAME}  user-name: testuser  password: passwd  https-hostname-verification-enabled: false
  automatic-reconnect: true  serverURIs:    - tcp://127.0.0.1:1883    spring:  h2:    console:      enabled: true      path: /h2  datasource:    url: jdbc:h2:mem:test    username: sa    password:     driver-class-name: org.h2.Driver