spring:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      continue-on-error: false
  main:
    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/llms/db/h2
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  mustache:    check-template-location: false
  flyway:
    url: jdbc:h2:~/llms/db/h2
    default-schema: PUBLIC
    schemas:    - PUBLIC
    user: sa    password: 
    locations:    - classpath:db/migration
    - filesystem:~/llms/db/migration
      
logging:
  level:
    '[org.atmosphere]': WARN
    
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.revo.llms