spring:
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      continue-on-error: false
  main:
    banner-mode: off
    log-startup-info: false
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:llms
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  mustache:    check-template-location: false
      
logging:
  level:
    '[org.atmosphere]': WARN
    
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.revo.llms